package in.finertia.fisheries.enums;

public enum MenuServiceType {
    HOME, FISHERS, FISHERMAN, FISH_VENDORS, BUYERS, SUPPLIERS, PMMSY_SCHEME, TRAINING_CALENDER, KNOWLEDGE_BASE, REAL_TIME_WEATHER, GRIEVANCES, NONE
}
